#! /bin/bash

usage() {
    echo "$0 - a script to fetch elasticsearch sources"
    echo "Options:"
    echo " -d - do fetch the code"
}

if [ "$1" != "-d" ]; then
    usage
    exit 1
fi

BASEDIR=$(readlink -f $(dirname "$0")/../)

mkdir -p "${BASEDIR}/SOURCES"
cd "${BASEDIR}/SOURCES"

spectool -g ../SPECS/elasticsearch.spec
